name: build-pdfs
concurrency: build-pdfs
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Images for slides
        run: mkdir -p build/transparencias && cp -R transparencias/img build/transparencias/img

      - name: Slides in HTML
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I transparencias/ -o build/transparencias/ --html --allow-local-files
        env:
          MARP_USER: root:root

      - name: Slides in PDF
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I transparencias/ -o build/transparencias/ --html --pdf --allow-local-files --theme-set styles/styles.css
        env:
          MARP_USER: root:root

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          working_directory: ejercicios
          continue_on_error: true
          latexmk_shell_escape: true

      - name: Compile LaTeX exams
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          working_directory: examenes
          continue_on_error: true
          latexmk_shell_escape: true
        continue-on-error: true

      - name: Copy pdf files
        run: |
          mkdir -p build/ejercicios  && cp ejercicios/*.pdf build/ejercicios
          mkdir -p build/examenes  && cp examenes/*.pdf build/examenes

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8">
            <title>Apuntes BBDD</title>
            <style>
              body { font-family: sans-serif; padding: 2em; }
              h1 { color: #444; }
              ul { list-style-type: none; padding-left: 0; }
              li { margin: 0.5em 0; }
              a { text-decoration: none; color: #007acc; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>📚 Apuntes de Bases de Datos</h1>' > build/index.html
      
          for dir in ejercicios examenes transparencias; do
            if [ -d build/$dir ]; then
              echo "<h2>📂 $dir</h2><ul>" >> build/index.html
              for file in $(find build/$dir -type f \( -name "*.pdf" -o -name "*.html" \) | sort); do
                name=$(basename "$file")
                echo "<li><a href=\"$file\">$name</a></li>" >> build/index.html
              done
              echo "</ul>" >> build/index.html
            fi
          done
      
          echo '</body></html>' >> build/index.html

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
